# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keystr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroke',
            name='email',
            field=models.EmailField(default='kishanmsagathiya@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stroke',
            name='timecsv',
            field=models.CommaSeparatedIntegerField(max_length=500),
        ),
    ]
